ログイン、ログアウト機能の追加 #2#3
taisei-13046/twitter pull request #10
Opened 2021-09-28 05:30 UTC by taisei-13046

### Issue

#2 #3 

### 内容

ログイン機能とログアウト機能を作成
またそれに対応するテストも作成

### 主な変更内容

user/urls.pyにてLoginView, LogoutViewを設定
また、setttings.pyにてログイン後のパス、ログアウト後のパスを設定

2021-09-29 02:14 UTC, taisei-13046 commented
<img width="670" alt="スクリーンショット 2021-09-28 14 30 28" src="https://user-images.githubusercontent.com/78260526/135191526-4568bfbf-a6fe-4b5f-a593-b034f3da74d4.png">
テストの実行結果

2021-09-29 02:15 UTC, taisei-13046 commented
<img width="1112" alt="スクリーンショット 2021-09-28 14 26 27" src="https://user-images.githubusercontent.com/78260526/135191593-40c8212a-8a48-4b12-bbb6-907eaca395a7.png"
<img width="1435" alt="スクリーンショット 2021-09-28 14 26 39" src="https://user-images.githubusercontent.com/78260526/135191598-d4900227-d4bf-4838-9a9f-71b18b148bd3.png">
<img width="1440" alt="スクリーンショット 2021-09-28 14 26 50" src="https://user-images.githubusercontent.com/78260526/135191608-ec69e4e0-79dc-4aa5-8b8d-fd16e0ee07cb.png">
>
<img width="1437" alt="スクリーンショット 2021-09-28 14 27 06" src="https://user-images.githubusercontent.com/78260526/135191624-0dba8c23-affb-4527-93fc-953e0b1273af.png">

サインイン、ログイン画面、home画面

2021-09-30 01:06 UTC, Akinori13 requested changes
いくつかコメントしました。

2021-09-30 01:06 UTC, Akinori13 commented on user/tests/test_views.py
> +class LoginTest(TestCase):
LoginとLogoutのテストでは、ユーザーがログインできているかのテストを、セッションやコンテクストを通して確認してください。

2021-09-30 01:06 UTC, Akinori13 commented on user/views.py
>  class LogoutView(TemplateView):
LogoutViewは必要ですか

2021-09-30 01:44 UTC, taisei-13046 commented on user/views.py
>  class LogoutView(TemplateView):
LogoutViewは必要ないです！

2021-09-30 06:31 UTC, taisei-13046 commented on user/tests/test_views.py
> +class LoginTest(TestCase):
self.assertIn(SESSION_KEY, self.client.session)
でsession_keyの確認をログイン前後で行なっています

2021-10-01 04:35 UTC, Akinori13 requested changes
logoutのURLを確認をお願いします。
また、現在はhomeにログインしていなくてもアクセスできます。これをログインしていない場合はアクセスできないようにしてみてください

2021-10-01 04:35 UTC, Akinori13 commented on user/urls.py
> +    path('home/logout/', auth_views.LogoutView.as_view(), name='logout'),
homeは必要なかったら消しちゃってください

2021-10-01 05:53 UTC, taisei-13046 commented
https://intellectual-curiosity.tokyo/2018/11/13/django%E3%81%AE%E3%83%AD%E3%82%B0%E3%82%A4%E3%83%B3%E5%87%A6%E7%90%86%E3%82%92%E5%AE%9F%E8%A3%85%E3%81%99%E3%82%8B%E6%96%B9%E6%B3%95%E2%91%A0/
Djangoのログイン処理を実装する方法①

2021-10-01 08:07 UTC, taisei-13046 commented
**また、現在はhomeにログインしていなくてもアクセスできます。これをログインしていない場合はアクセスできないようにしてみてください**

→ ユーザ情報の有無で表示する内容を変更しました

2021-10-01 11:54 UTC, Akinori13 requested changes
コメントしました

2021-10-01 11:54 UTC, Akinori13 commented on user/templates/user/home.html
> +{% if user.is_authenticated %}
この方法を全てのページで実装するのは大変になります。
LoginRequiredMixinというのがDjangoには用意されています。こちらを使ってみてください

2021-10-01 11:54 UTC, Akinori13 commented on user/templates/user/home.html
> +{% if user.is_authenticated %}
LOGIN_URLを設定することを忘れずに！

[参照](https://docs.djangoproject.com/en/3.2/ref/settings/#login-url)

2021-10-02 08:14 UTC, taisei-13046 commented on user/templates/user/home.html
> +{% if user.is_authenticated %}
https://qiita.com/kozakura16/items/f6877a3376f03a07589f
参考にしたサイト

2021-10-03 02:46 UTC, Akinori13 commented
lgtm

2021-10-05 06:43 UTC, fumiharun11 reviewed
全体的に良いと思います！
細かい点についてコメントしたので確認お願いします！

2021-10-05 06:43 UTC, fumiharun11 commented on user/tests/test_views.py
> +        self.response = self.client.post(url, data)
この`setUp`メソッドで処理している内容は必要？

2021-10-05 06:43 UTC, fumiharun11 commented on user/tests/test_views.py
> +        """短いパスワードのユーザを作成"""
このdocstringはメソッドで実施している内容に対して適切？
どちらかというとクラスに対するdocstring？

2021-10-06 01:40 UTC, taisei-13046 commented on user/tests/test_views.py
> +        self.response = self.client.post(url, data)
setupの記載がない場合、ログインしていない状態では/homeに遷移できないため必要だと考えます

2021-10-06 01:53 UTC, fumiharun11 commented on user/tests/test_views.py
> +        self.response = self.client.post(url, data)
この`setUp`メソッドで実施している処理は、サインアップ機能の実装に大きく依存したものになっていると考えます。現状の書き方はunittestではなくユーザーストーリーに沿ったフローを想定していますか？

ここでの前提条件はログインしていることなので、以下の方針に変更してください。
1. `setUpTestData`メソッド内でログイン用のユーザーを作成する処理を記述する
2. `setUp`メソッド内で`self.client.login(...)`を実行し`self.client`にログインさせる

参考: https://docs.djangoproject.com/en/3.2/topics/testing/tools/#django.test.TestCase.setUpTestData

2021-10-06 03:23 UTC, taisei-13046 commented on user/tests/test_views.py
> +        self.response = self.client.post(url, data)
・setUpTestData()を使った方が実行結果が速くなる

2021-10-06 03:25 UTC, taisei-13046 commented
修正点
・HomeViewTestsとRedirectNotLoginUserクラスにsetUpTestDataを適応した形で書き換えた

2021-10-06 03:53 UTC, fumiharun11 approved these changes
LGTM

2021-10-06 03:53 UTC, merged