ツイート機能の追加　Tweet #5
taisei-13046/twitter pull request #12
Opened 2021-10-10 06:24 UTC by taisei-13046

### 変更点
- 新たにアプリケーション(blog)を作成して、tweetに関する内容はここで処理した。
- modelを設定し、CURD操作を作った
- それに伴いテストを書いた

2021-10-12 07:00 UTC, Akinori13 requested changes
いくつかコメントしました

2021-10-12 07:00 UTC, Akinori13 commented on blog/templates/blog/home.html
> +      <p>コメント：{{post.content}}</p>
linebreaksbrを使うことで改行できます

2021-10-12 07:00 UTC, Akinori13 commented on blog/tests.py
> +        self.user2_tweet = Post.objects.create(content='user2', author=self.user2)
テストを繰り返し実行すると、成功しない場合があると思います。これは、user1_tweetができる前にuser2_tweetができることがあるからです。
これを避けるために、`time.sleep(0.1)`を挿入してください

2021-10-12 07:00 UTC, Akinori13 commented on requirements.txt
> +pillow
必要ないなら消しちゃってください

2021-10-13 08:41 UTC, taisei-13046 commented
<img width="746" alt="スクリーンショット 2021-10-13 17 41 21" src="https://user-images.githubusercontent.com/78260526/137098602-651dccc6-1519-40aa-9973-67b1cee4928f.png">

2021-10-13 08:42 UTC, taisei-13046 commented
<img width="595" alt="スクリーンショット 2021-10-13 17 42 17" src="https://user-images.githubusercontent.com/78260526/137098734-3a8b2e26-70ef-423f-a0f9-70a7d5e30306.png">

2021-10-13 08:46 UTC, taisei-13046 commented on blog/templates/blog/home.html
> +      <p>コメント：{{post.content}}</p>
改行ではなく、borderlineを引く目的で使っています

2021-10-14 06:10 UTC, taisei-13046 commented
hrタグについて
-> 改行ではなく、borderlineを引く目的で使っています

2021-10-17 13:30 UTC, Akinori13 commented on blog/templates/blog/home.html
> +      <p>コメント：{{post.content}}</p>
こちらですが、Linebreaksbrを使うことで、改行のあるpost.contentであっても改行して表示することが可能になります。
現状では、
```
hello!
world!
```
と入力しても、`hellow!world!`と表示されると思います。

[参考サイト](https://qiita.com/nachashin/items/d3f9cd637a9cecbda72c)
[公式サイト](https://docs.djangoproject.com/en/3.2/ref/templates/builtins/)

2021-10-17 14:00 UTC, Akinori13 commented
LGTM

2021-10-18 17:12 UTC, fumiharun11 commented on blog/tests.py
> +    def test_with_over_max_length(self):
前提条件が`CreateTweetTest`と同等なのですが、テストケースクラスを分けている理由について教えてもらえますか？

2021-10-18 17:12 UTC, fumiharun11 commented on twitter/settings.py
> +    # 'blog',
このコメントアウト残している理由は？

2021-10-18 17:12 UTC, fumiharun11 commented on twitter/settings.py
> +MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
os.pathを用いずpathlibのフォーマットで表現することは不可能だった？

2021-10-18 17:12 UTC, fumiharun11 commented on blog/views.py
> +    form_class = PostCreateForm
Update用のViewにはUpdate用のFormを渡す設計になっていると良いと思います。

2021-10-19 02:53 UTC, taisei-13046 commented on twitter/settings.py
> +    # 'blog',
エラー原因を究明するときの残骸でした

2021-10-19 02:55 UTC, taisei-13046 commented on blog/tests.py
> +    def test_with_over_max_length(self):
確かに同等でした！
CreateTweetTestと統合します

2021-10-19 03:01 UTC, taisei-13046 commented on twitter/settings.py
> +MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
一旦mediaは使わない(写真の投稿はしない)方針にしたので、この部分は消去します

2021-10-20 01:29 UTC, taisei-13046 commented on blog/views.py
> +    form_class = PostCreateForm
CreateのFormと同等ですが、それでも分けた方がいいでしょうか？
それともPostCreateFormではなく、PostTweetFormとかにしてCreateとUpdateで共通化したほうがいいでしょうか？

2021-10-20 06:32 UTC, fumiharun11 commented on blog/forms.py
> +class PostUpdateForm(forms.ModelForm):
IMO: 仕様上`PostCreateForm`と全く同じ設計になるのであれば、共通化のクラスを作成して継承する方針や`PostCreateOrUpdateForm`という命名のフォームクラスを作成する方針を採っても良いと思います。
以下は共通化のクラスを作成した際の例です。
```py
class PostFormBase(forms.ModelForm):
    class Meta:
        model = Post
        ...

class PostCreateForm(PostFormBase):
    pass

class PostUpdateForm(PostFormBase):
    pass
```

2021-10-20 06:40 UTC, fumiharun11 approved these changes
LGTM

2021-10-20 06:40 UTC, merged