Re follow #6
taisei-13046/twitter pull request #13
Opened 2021-11-16 05:53 UTC by taisei-13046

2021-11-16 05:54 UTC, taisei-13046 commented
デモ動画

https://user-images.githubusercontent.com/78260526/141928927-95a0c78e-a300-41c0-9dd0-269959062d65.mov

2021-11-16 05:57 UTC, taisei-13046 commented
https://user-images.githubusercontent.com/78260526/141929278-bb84c8d6-8b38-4a8c-bd59-158302384471.mov

2021-11-17 13:12 UTC, Akinori13 requested changes
コメントしました。

2021-11-17 13:12 UTC, Akinori13 commented on blog/views.py
> +class FollowAllowView(ListView):
一つにまとめるよりも、FollowViewとUnfollowViewに分離したり、リクエストメソッドごとに分離する方が、機能が明確になるのでベターです。

2021-11-17 13:12 UTC, Akinori13 commented on blog/views.py
> +class FollowAllowView(ListView):
またFollowAllowViewは「フォローを許可する」といった機能を連想する場合があるので、シンプルにFollowViewでよいかと思います！

2021-11-18 09:39 UTC, taisei-13046 commented on blog/views.py
> +class FollowAllowView(ListView):
@Akinori13 リクエストごとに分離する形にしました

2021-11-20 06:38 UTC, Akinori13 commented on blog/views.py
> +class FollowAllowView(ListView):
## リクエストメソッドごとに分離
HTTPリクエストメソッドは、GET, POST, PUT, DELETEなどがあり、これらを使い分けることでURLだけではなくメソッドにより処理を分けることができます。
今回の機能であれば、POSTメソッドであればFollowViewの中でfollowを、DELETEメソッドであればFollowViewの中でunfollowを実行します。
上記のようなことは、Django REST frameworkを用いる方が簡単になります。（もちろん`request.method == 'POST'`のように実装することも可能ではあります。）
今回はDRFを用いないので、FollowViewとUnfollowViewの二つに分けましょう。
## フォロー機能
フォロー機能はBLOGアプリより、USERアプリの方が自然だと思います。
## テスト
修正後はテストを実行するようにお願いします。

2021-12-09 10:57 UTC, taisei-13046 commented
### リクエストメソッドごとに分離について
この方針で一度進めましたが、1つのHTML上でFollowとUnFollowをすることができないため、
現状のFollowViewでどちらの操作もするようにしました。
これに関しては,DRFではHTTPメソッドごとに分ける必要性を感じましたが、今回の場合はこのような形でも問題ないかと思いました！ご指摘ありがとうございます！

### Follow機能をUserへ移す
これは対応をしました

2021-12-09 10:57 UTC, taisei-13046 commented
<img width="666" alt="スクリーンショット 2021-12-09 19 39 00" src="https://user-images.githubusercontent.com/78260526/145383995-bfd07c32-4c05-415f-bf6c-acc1e0a4deeb.png">

2021-12-14 14:14 UTC, Akinori13 requested changes
コメントに時間がかかり申し訳ないです。
FollowViewとUnFollowViewに分けることをお願いします。（実装の方針を書きましたが、難しい箇所なので、質問があればぜひ！）
難しい箇所ですが、自分自身をフォローしようとした場合や存在しないユーザーをフォローしようとした場合も網羅的に考慮していて、とてもいいなと思っています！

2021-12-14 14:14 UTC, Akinori13 commented on blog/views.py
> +        context['post_list'] = post_list
このレベルであれば、わざわざ分けなくても大丈夫です
例
```suggestion
        context['following_count'] = Follow.objects.filter(follow_from=login_user).count()
```

2021-12-14 14:14 UTC, Akinori13 commented on blog/tests.py
> +class FollowTest(TestCase):
自分自身に対してリクエストを送信した場合と、存在しないユーザーに対してリクエストを送信した場合、フォローしていないユーザーに対してフォロー解除リクエストを送信した場合のテストを実装してください

2021-12-14 14:14 UTC, Akinori13 commented on user/views.py
> +			return HttpResponseNotFound('<h1>自分自身をフォローすることはできません</h1>')
403で返してあげてください

2021-12-14 14:14 UTC, Akinori13 commented on user/views.py
> +				if follow_relation.count() == 0:
これで確認してください
```suggestion
				if follow_relation.count():
```

2021-12-14 14:14 UTC, Akinori13 commented on user/views.py
> +		if request.user.id is not None:
これ必要ですか

2021-12-14 14:14 UTC, Akinori13 commented on user/views.py
> +class FollowView(ListView):
やはりバグ回避のために異なる機能はなるべく分けるようにしてください。
例えば44行目`HttpResponseNotFound('<h1>自分自身をフォローすることはできません</h1>')`は自分自身をアンフォローしようとしたときにも表示されます。これが表示される可能性は低いとても低いですが、バグ回避のために異なる機能はなるべく分けることを常に意識してください。

実装の方針としてはformタグのactionを指定することです。参照としては[こちらのチュートリアル](https://docs.djangoproject.com/ja/3.2/intro/tutorial04/)をチェックしてみてください。難しい箇所だと思うので頑張って取り組んでみましょう！

2021-12-14 14:14 UTC, Akinori13 commented on user/views.py
> +class FollowView(ListView):
あとログイン必須にしてください

2021-12-14 14:14 UTC, Akinori13 commented on blog/tests.py
> +    def test_fail_create_follow(self):
命名はどんな時に失敗するか一目でわかるようにつけてください。ある程度長くなっても構いません。

2021-12-16 01:27 UTC, taisei-13046 commented
<img width="536" alt="スクリーンショット 2021-12-16 10 27 02" src="https://user-images.githubusercontent.com/78260526/146291039-a7cebc25-ae95-425d-9fe8-22da79d3bf78.png">
test 実行結果

2021-12-16 01:41 UTC, taisei-13046 commented
### 方針
今までクラスでFollow, UnFollow機能を作成しようとしていましたが、汎用Viewを使用するとやりずらさを感じたため**関数VIew**で書く方針に切り替えました
その結果、とてもスムーズに書くことができたのですがこの方針はどうでしょうか
関数Viewに切り替えた理由
- ClassViewだとある程度決まった形があるため自由度が低い
- django.views.generic.base.Viewを継承するなら関数Viewで書いてもそこまで変わらない( 可読性等の面において )

##### 今後のスタンス
基本はクラスViewで書いていき、細かい処理やtemplateが必要ない処理などは関数Viewで処理する

2021-12-20 05:01 UTC, Akinori13 requested changes
数点コメントしました。確認お願いします。

2021-12-20 05:01 UTC, Akinori13 commented on blog/templates/blog/follower.html
> +</nav>
ここは共通だと思うので今後はcommonフォルダを作成してbase.htmlなどに組み込むといいと思います。

2021-12-20 05:01 UTC, Akinori13 commented on blog/urls.py
> +    path('<str:username>/follower/', views.FollowerListView.as_view(), name="follower"),
機能としてはuserアプリケーションかなと思います

2021-12-20 05:01 UTC, Akinori13 commented on user/urls.py
>      path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name="login"),
これが適切に動いているのかを確認してもらいたいです。

2021-12-20 05:01 UTC, Akinori13 commented on user/templates/user/follow_index.html
> +</nav>
このファイル含めてヘッダーなどの共通部分はまとめた方が良いです。[参考](https://tutorial.djangogirls.org/ja/template_extending/)

2021-12-20 05:01 UTC, Akinori13 commented on blog/views.py
> +        context['following_list'] = User.objects.filter(id__in=following_list)
```suggestion
       context['following_list'] = user.following.all()
```
でも可能だと思います。呼び出し時は`{{following.follow_to}}`になりますが。

2021-12-20 05:01 UTC, Akinori13 commented on blog/tests.py
> +        self.assertEqual(following_count, 0)
followのテストとunfollowのテストが混ざっています。FollowTestとUnfollowTestに分割するか、テスト名に含めるなど可読性を高めてください。

2021-12-20 05:01 UTC, Akinori13 commented on user/views.py
> +		follower = request.user
ここはtryに入れなくていいのではないでしょうか

2021-12-20 05:01 UTC, Akinori13 commented on user/views.py
> +	return HttpResponseRedirect(reverse_lazy('blog:home'))
https://as-chapa.hatenablog.com/entry/django-render

2021-12-20 05:01 UTC, Akinori13 commented on user/views.py
> +class FollowIndexView(ListView):
Login必須化

2021-12-20 15:32 UTC, taisei-13046 commented
<img width="676" alt="スクリーンショット 2021-12-21 0 31 50" src="https://user-images.githubusercontent.com/78260526/146792384-3e649f3b-0909-4cd2-a885-ed94ec42a11e.png">

2021-12-20 15:54 UTC, taisei-13046 commented on user/urls.py
>      path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name="login"),
https://user-images.githubusercontent.com/78260526/146795544-f8adbdaa-cc46-461a-9e20-3360dffb0132.mov

2021-12-23 02:00 UTC, Akinori13 requested changes
数点コメントしました。

2021-12-23 02:00 UTC, Akinori13 commented on blog/templates/blog/blog_header.html
> +<body>
ここは<header>で

2021-12-23 02:00 UTC, Akinori13 commented on user/views.py
> +		can_follow = Follow.objects.filter(follow_to=target_user, follow_from=login_user).count() == 0
can_followだとfollowする権限チェックのように感じるので、has_followedとかでもいいんじゃないでしょうか。（trueとfalseが反対になりますが。）

2021-12-23 02:00 UTC, Akinori13 commented on user/views.py
> +		same_user = login_user == target_user
ここは変数名を再考しましてください。booleanを返す場合は、`is_~`、`has_~`や`can_~`が望ましいでしょう

2021-12-23 02:00 UTC, Akinori13 commented on user/views.py
> +class FollowIndexView(LoginRequiredMixin, ListView):
ListViewでしょうか

2021-12-23 02:00 UTC, Akinori13 commented on user/templates/follow/follow_index.html
> +</div>
削除

2021-12-23 02:00 UTC, Akinori13 commented on blog/templates/blog/blog_header.html
> +<body>
```suggestion
<header>
```

2021-12-23 03:40 UTC, taisei-13046 commented on user/views.py
> +class FollowIndexView(LoginRequiredMixin, ListView):
TemplateViewに変更しました!!

2021-12-23 07:08 UTC, Akinori13 approved these changes
LGTM

2021-12-24 10:26 UTC, fumiharun11 commented on user/models.py
> +    follow_from = models.ForeignKey(User, on_delete=models.CASCADE, related_name="following")
フィールド名を`following`や`follower`にしていないのは理由がある？

2021-12-24 10:26 UTC, fumiharun11 commented on user/views.py
> +		has_followed = Follow.objects.filter(follow_to=target_user, follow_from=login_user).count() != 0
plz use [exists()](https://docs.djangoproject.com/en/3.2/ref/models/querysets/#django.db.models.query.QuerySet.exists)
```suggestion
		has_followed = Follow.objects.filter(follow_to=target_user, follow_from=login_user).exists()
```

2021-12-24 10:26 UTC, fumiharun11 commented on user/views.py
> +	return HttpResponseRedirect(reverse('blog:home'))
参考: ショートカット関数 [redirect()](https://docs.djangoproject.com/en/3.2/topics/http/shortcuts/#redirect)
修正は任意で大丈夫です。

2021-12-24 10:26 UTC, fumiharun11 commented on user/views.py
> +	if not follow_relation.count():
exists()

2021-12-24 10:26 UTC, fumiharun11 commented on user/views.py
> +	if follow_relation.count():
exists()

2021-12-24 10:26 UTC, fumiharun11 commented on user/templates/follow/follower.html
> +            <h4>{{follower.follow_from}}</h4>
一見処理に問題は無さそうですが、N回SQLが発行されている可能性があります。
N+1問題で調べてみてください。

2021-12-25 00:44 UTC, taisei-13046 commented on user/models.py
> +    follow_from = models.ForeignKey(User, on_delete=models.CASCADE, related_name="following")
フィールド名をfollowing, followerにしていない理由は個人的にどっちがどっちかわからなくなるため、
follow_fromの方がわかりやすいと思ったからです。
ただ、改めてみるとrelated_nameと違うのは違和感があるので、どちらもfollow_fromの形に修正します

2021-12-25 01:35 UTC, taisei-13046 commented on user/views.py
> +	return HttpResponseRedirect(reverse('blog:home'))
redirectはHttpResponseRedirectを返すメソッドで、HttpResponseRedirectを使うよりも短く、より多くの引数を取れるのがメリットって感じですかね。。。
ありがとうございます

2021-12-25 05:36 UTC, taisei-13046 commented on user/templates/follow/follower.html
> +            <h4>{{follower.follow_from}}</h4>
![スクリーンショット 2021-12-25 14 09 20](https://user-images.githubusercontent.com/78260526/147378193-657b75c6-8d2b-4d85-83cb-82f6403604f2.png)
N+1問題を解消しました

2021-12-26 13:33 UTC, fumiharun11 commented on user/templates/follow/follower.html
> +    {% for list in follower_list %}
変数`list`のtypeはlistではないので変数名は適したものに変更しましょう。

2021-12-26 13:33 UTC, fumiharun11 commented on user/templates/follow/following.html
> +    {% for list in following_list %}
同様

2021-12-26 13:33 UTC, fumiharun11 commented on user/templates/follow/follow_index.html
> +        <form method="POST">
見逃していたのですが、formタグを記述しているのは何故ですか？

2021-12-26 13:33 UTC, fumiharun11 commented on user/views.py
> +		context['following_list'] = user.following.all().select_related('follower')
`select_related()`を用いる方針を採用したのは良いですね:+1:
補足: 実装方針的に`values_list()`や`values()`を用いても良さそうなので余裕があれば調べてみてください。

2021-12-26 13:33 UTC, fumiharun11 commented on user/models.py
> +    following = models.ForeignKey(User, on_delete=models.CASCADE, related_name="following")
- `follow_from`→`following`
- `follow_to`→`follower`

変更されたフィールド名について、上記の対応関係って合っていますか？
以下の対応関係の認識だったのですが...

- `follow_from`→`follower`
- `follow_to`→`following`

2021-12-26 13:33 UTC, fumiharun11 commented on user/models.py
> +    follow_from = models.ForeignKey(User, on_delete=models.CASCADE, related_name="following")
> フィールド名をfollowing, followerにしていない理由は個人的にどっちがどっちかわからなくなるため、
follow_fromの方がわかりやすいと思ったからです。

確かに`following`が関係上『フォローされている人』を表すと認識していないと混乱を招きそうですね。
(それでも開発者自身が判別しにくい場合は、そもそもそのような命名を避けるのも良さそうです)
よく`follower`と`followee`といった関係性の命名も使用されるので、そちらも参考にしてみてください。

2021-12-26 14:26 UTC, taisei-13046 commented on user/models.py
> +    following = models.ForeignKey(User, on_delete=models.CASCADE, related_name="following")
`follow_from`はfollowする主体
`follow_to`はfollowする相手
という認識で使っていたため、
`follow_from` -> `following`
`follow_to` -> `follower`
という変更を行いました。

```
follow_from = models.ForeignKey(User, on_delete=models.CASCADE, related_name="following")
```
変更前の状態でもそのように定義していました。

2021-12-26 14:37 UTC, taisei-13046 commented on user/templates/follow/follow_index.html
> +        <form method="POST">
ここのformの記述は必要ありませんでした！
初期の方針の残りが残ってしまっていました

2021-12-26 14:41 UTC, taisei-13046 commented
<img width="669" alt="スクリーンショット 2021-12-26 23 40 19" src="https://user-images.githubusercontent.com/78260526/147411502-2da46081-07ca-4fd9-868a-9edd4ed92d77.png">

2021-12-26 15:46 UTC, fumiharun11 commented on user/models.py
> +    following = models.ForeignKey(User, on_delete=models.CASCADE, related_name="following")
以下のコミットでフィールド名の変更に関連する処理の変数名等も変更してもらっていますが、変更前は`Follow`インスタンス生成時に`request.user`を`follower`として以下のような形式で引数に渡していました。
変更前までは`follower`がfollowする主体の認識だったのですが、以下のコミットで`following`がfollowする主体の認識に変わったと判断して良いですか？

https://github.com/taisei-13046/twitter/pull/13/commits/e6b673baa579700d7916916d2f8113a95c9618ff#diff-766d81bd31b085813d7dd0f8e43f3278bb2f7cd8c5900ab4b9838b64d813ad31L66-R75

```python
follower = request.user
...
new_follow = Follow(follow_to=following, follow_from=follower)
```

2021-12-27 00:35 UTC, taisei-13046 commented on user/models.py
> +    following = models.ForeignKey(User, on_delete=models.CASCADE, related_name="following")
当初から、followingがfollowする主体だと考えていましたが、上記のcommitまで`new_follow = Follow(follow_to=following, follow_from=follower)`と間違えて記述していました。
`follow_from` -> `following`に治す指摘をいただいた時点で、その間違いに気づいて修正した次第です。

なので質問の回答としては、
当初からfollowingがfollowする主体という認識ではあったが、コードを記述する上でその立場が逆転していることに気づいておらず、上記のcommitの際にそれに気づき修正した。
ということになります。
紛らわしくすみません

2021-12-27 01:01 UTC, fumiharun11 approved these changes
LGTM

2021-12-27 01:01 UTC, merged