いいね機能の実装 Like #6
taisei-13046/twitter pull request #14
Opened 2021-12-27 01:54 UTC by taisei-13046

https://h-memo.com/how-to-make-a-like-button-using-django/
基本的には上記の記事を参照して作成しました。
記事との違いは、機能をlikeとunlikeに分けている点です。

テスト実行結果です
<img width="700" alt="スクリーンショット 2021-12-27 10 44 34" src="https://user-images.githubusercontent.com/78260526/147426400-408401e6-4f31-421e-b1ed-2d6cecc6eae6.png">

csrfTokenに関しては
https://github.com/taisei-13046/TIL/blob/main/react/React_day2_cookie.md
このように理解しています

2021-12-28 16:45 UTC, Akinori13 requested changes
いくつかコメントしました。確認お願いします

2021-12-28 16:45 UTC, Akinori13 commented on blog/views.py
>          context['post_list'] = Post.objects.all()
like.htmlでpost.like_set.countしているので、prefetch_related用いてはいかがでしょうか

2021-12-28 16:45 UTC, Akinori13 commented on blog/views.py
> +    if request.is_ajax():
今回はJsonResponseしかないので消しちゃってもいいと思います

2021-12-28 16:45 UTC, Akinori13 commented on blog/views.py
> +        'post_id': post.id,
これって必要でしたか？

2021-12-28 16:45 UTC, Akinori13 commented on blog/templates/blog/like.html
> +    <a id="like" href="javascript:void(0);" name="{{post.id}}" data-url="{% url 'blog:like' post.pk %}" type="button">
documentに一つのものにidを振ります。cssのために必要な場合はclassを用いてください。
またnameにpost.idを振るのも少しname属性の使い方と異なるのかなと思いました。ここはurl同様にdata属性を用いるのが良いかと思います。

2021-12-28 16:45 UTC, Akinori13 commented on static/js/ajax.js
> +});
ここはjQueryのajaxではなくFetchで書き換えてもらいたいです。
またJavaScriptではvarではなくletとconstを使ってみてください。CSRFの部分はDjangoの公式ドキュメントのままで構いません。

2021-12-28 16:45 UTC, Akinori13 commented on blog/tests.py
> +    def test_with_success_unfollow(self):
命名確認お願いします！

2021-12-28 16:45 UTC, Akinori13 commented on blog/tests.py
> +class LikeTest(TestCase):
LikeTestもUnlikeTestも実際に返ってくるデータが適切なだけでなく。DB上で削除されているのか作成されているのかのチェックをお願いします。

2021-12-28 16:45 UTC, Akinori13 commented on blog/tests.py
> +class UnlikeTest(TestCase):
blog:likeにpostしてデータを作成するのではなく、setUpでDBにいいねを作成しておく形が良いと思います。

2021-12-29 02:25 UTC, taisei-13046 commented on blog/views.py
> +        'post_id': post.id,
ajax内のresponseで使用しています
`            selector = document.getElementsByName(response.post_id);
`など

2021-12-29 03:07 UTC, Akinori13 commented on blog/views.py
> +        'post_id': post.id,
@taisei-13046 
なるほど！！見落としていました。ありがとうございます。
Fetchを使ってもらいますが、jQueryにもコメントします。
ajax.jsのsuccess内ですが、ここは非同期的に動作しているので、もう一度selectorを設定する必要はなく、そのまま`$(this)`を使うことができます。
ただし、`$(this)`は最も近いイベントを拾ってしまうので、$.ajax前で、
```
~
const split_url = $(this).attr('data-url').split('/');
const el = $(this);
```
のようにしてあげると、success内で`el`を用いることができます。

2021-12-29 07:54 UTC, taisei-13046 commented
<img width="650" alt="スクリーンショット 2021-12-29 16 53 51" src="https://user-images.githubusercontent.com/78260526/147639577-9967aa3b-f160-4be6-b137-86fdabd7efa0.png">

2021-12-30 03:10 UTC, Akinori13 requested changes
２点コメントしました。確認お願いします。

2021-12-30 03:10 UTC, Akinori13 commented on blog/views.py
> +        context['post_list'] = Post.objects.prefetch_related('like_post').all()
ここはpost.authorをしているので、select_relatedも使ってもいいと思います

2021-12-30 03:10 UTC, Akinori13 commented on static/js/ajax.js
> +                el.html("<i class='fas fa-lg fa-heart like-red'></i>");
パフォーマンス的にも子要素（`<i>`）のclassの置き換えでも対応できると思います

2021-12-30 12:39 UTC, Akinori13 commented
LGTM

2022-01-04 02:10 UTC, fumiharun11 commented on static/js/ajax.js
> +    var cookieValue = null;
このファイル内における`var`は全て`let` or `const`にreplaceしましょう。

2022-01-04 02:10 UTC, fumiharun11 commented on static/js/ajax.js
> +    async function PostData(){
関数命名であればlowerCamelCaseにしましょう

2022-01-04 02:25 UTC, fumiharun11 approved these changes
LGTM

2022-01-04 02:25 UTC, merged