ユーザ登録機能の実装 #1
taisei-13046/twitter pull request #9
Opened 2021-09-11 07:46 UTC by taisei-13046

### Issue
#1 

### 内容

- ユーザ名、メールアドレス、パスワードによってユーザを作成
- 参考にした記事: https://qiita.com/onishi_820/items/f8d7cfe0deb828c40381

2021-09-12 04:37 UTC, Akinori13 requested changes
いい感じです！
参考にした記事も載せてくれてありがとうございます。
①いくつかのファイル・フォルダーは`.gitignore`で指定してgit管理しないので、管理から外してその設定を反映させてください。
```
*.pyc
__pycache__
db.sqlite3
.DS_Store
```
今回は`.idea`も管理対象から外してください。

②ユーザー登録機能のテストも書いてみてください。
以下を少なくともテストしてください
- GETリクエストした時にtemplateが表示されるか。
- POSTリクエストした時にユーザー登録されるか。
- 短すぎるパスワードでPOSTリクエストした時にエラーがきちんとでるか。

2021-09-12 04:37 UTC, Akinori13 commented on user/templates/user/login.html
> +{% endblock %}
ファイルの最終行は空行にする必要があります。改行をしなければ、その行が正しく読み込まれないことがあるからです。
最終行を空行にして、ストップマークがでないようにしてください。
ここ以外も複数あると思うので修正してください

2021-09-13 05:22 UTC, taisei-13046 commented on user/templates/user/login.html
> +{% endblock %}
こちらに関しては、pycharmの設定の変更によってセーブごとに１行開業するように設定しました

2021-09-13 12:13 UTC, taisei-13046 commented
![スクリーンショット 2021-09-13 21 11 40](https://user-images.githubusercontent.com/78260526/133081234-a6fac773-0ca2-48f8-8a8c-8bc077ad8140.png)
動作画面

2021-09-13 12:14 UTC, taisei-13046 commented
<img width="632" alt="スクリーンショット 2021-09-13 21 13 45" src="https://user-images.githubusercontent.com/78260526/133081499-77e1e2c2-c4c5-404e-bd25-e17589fb5a16.png">
テスト完了

2021-09-13 12:22 UTC, taisei-13046 commented
変更点

**テストの作成**

- GETリクエストした時にtemplateが表示されるか。
- POSTリクエストした時にユーザー登録されるか。
- 不適切なユーザでPOSTリクエストした時にエラーがでるか。

2021-09-14 13:31 UTC, Akinori13 requested changes
いくつかコメントしました
- `.idea`はいらないので、.gitignoreに追記してください。
- __pycache__なども同様に管理対象から外したことを確認してください。
- requirements.txtを書いてください。（django girlsなどを参考に）
- 仮想環境でmyvenvなどを使うと思うので、その際は.gitignoreに追記してください。

2021-09-14 13:31 UTC, Akinori13 commented on user/tests/test_views.py
> +class InvalidSignUpTests(TestCase):
テスト自体は綺麗に書けており、とても良いと思います。
一方で簡単すぎるパスワードや短すぎるパスワードの場合にエラーが返されるかのテストも実行してもらいたいです。

2021-09-14 13:31 UTC, Akinori13 commented on user/views.py
> +from django.shortcuts import render
これ使っていないので消しちゃってください

2021-09-14 13:31 UTC, Akinori13 commented on user/urls.py
> +from django.urls import path, include
includeは使ってないので消しちゃってください

2021-09-14 14:01 UTC, taisei-13046 commented
- .ideaはいらないので、.gitignoreに追記してください。
- __pycache__なども同様に管理対象から外したことを確認してください。

これらは前回.gitignoreに追記したにもかかわらず、gitの管理から外れていなかったようですので
https://qiita.com/Potof_/items/c75eba9cfa72819506de (.gitignore の設定を反映させる)
こちらを参考にキャッシュを消去する作業をしました
やるべきこととしては正しいでしょうか？

2021-09-17 16:06 UTC, Akinori13 requested changes
いくつかコメントしました。

2021-09-17 16:06 UTC, Akinori13 commented on requirements.txt
> +Django~=2.2.5
installしたものはすべて記載します。
`django-widget-tweaks`を追記してください。

2021-09-17 16:06 UTC, Akinori13 commented on requirements.txt
> +Django~=2.2.5
Djangoのバージョンは現在LTSの3.2にしてください。

2021-09-19 11:46 UTC, taisei-13046 commented on requirements.txt
> +Django~=2.2.5
バージョンの指定がなかったので、特にバージョンの記載はしませんでした

2021-09-21 10:12 UTC, Akinori13 commented
lgtm

2021-09-21 10:33 UTC, fumiharun11 commented on user/tests/test_views.py
> +class InvalidSignUpTests(TestCase):
`UserCreationform`を継承したフォームを使用しているので、他に想定されるエラーについてもテストの記述をお願いします。

2021-09-22 13:17 UTC, taisei-13046 commented
<img width="706" alt="スクリーンショット 2021-09-22 22 16 44" src="https://user-images.githubusercontent.com/78260526/134350660-fcf526e9-1a9f-4fec-8dac-7d3c1cacbe4f.png">

テスト結果 2021/9/22

2021-09-24 10:53 UTC, fumiharun11 reviewed
テストについて確認しました。
アクション毎にメソッドを生成してステータスコードやフォームエラーのテストを実施するのではなく、全てのアクションに対してステータスコードだけ、フォームエラーだけをテストするようなメソッドを生成する方針にしたことはコードを見て確認しました。

この方針はコメント時に意図したものではないですが、一つの方針として有りだと思います。
ただし、一部のエラーパターンだけ他のエラーと異なる挙動が発生するような場合はこのフォーマットだと確認しなければならない箇所が散らばってしまう(特にテスト数が多くなるほど顕著になる)ので注意する必要があると考えています。

また、ユーザー名が全て`example`を前提にテストしていますが、これについてのinvalidパターンも書いてみましょう。

最後に、コメント時に意図した方針について今回記述されたケースを参考に一つ例を記載します。修正は必須ではないです。
```py
class InvalidSignUpTests(TestCase):
    def setUp(self):
        self.url = reverse('user:signup')

    def test_post_failed_invalid_email(self):
        form_data = {
            'username': 'example',
            'email': 'sample',
            'password1': '12345678',
            'password2': '12345678',
        }
        res = self.client.post(self.url, form_data)
        self.assertEquals(res.status_code, 200)
        self.assertTrue(res.context.get('form').errors)
        self.assertFalse(User.objects.filter(username='example').exists())
```

2021-09-24 10:53 UTC, fumiharun11 commented on user/tests/test_views.py
> +import unittest
未使用に見えますがimportした理由はなんですか？

2021-09-24 10:53 UTC, fumiharun11 commented on user/tests/test_views.py
> +class NoneSignUpTests(TestCase):
`None`というより`EmptyPost`？

2021-09-24 10:53 UTC, fumiharun11 commented on user/tests/test_views.py
> +        self.assertFalse(User.objects.exists())
テーブルのレコードが空であることを前提に作成されたテストのようだけど、後でsetUp時にテストレコードが追加されたらこのテストは機能しなくなってしまう可能性が高いので、filterの条件付けをchainしてあげましょう。

2021-09-28 05:02 UTC, fumiharun11 approved these changes
LGTM

2021-09-28 05:11 UTC, merged